In [1]:
import numpy as np

#### 1. Write a NumPy program to create 1D array as arr=[[1,2,3],[4,5,6]]

In [2]:
arr=np.array([[1,2,3],[4,5,6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### 2. Write a NumPy program to test whether none of the elements of a arr is zero

In [4]:
print(np.all(arr))

True


#### 3. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [5]:
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[ 0.25473018 -1.40229773 -0.14283222 -0.42003285  0.67651741 -1.40841462
  1.07350812  1.17311285  0.21123859  0.48765828 -0.75225159 -1.53069298
 -0.12564771 -1.1444921   0.45410759]


#### 4. Write a NumPy program to create an array of all the even integers from 30 to 70

In [6]:
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### 5. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [7]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### 6. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10  Expected Output [[2,3,4],[5,6,7],[8,9,10]]

In [8]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 7.Write a NumPy program to convert a list and tuple into arrays. Go to the editor List to array:
[1 2 3 4 5 6 7 8] <br>
Tuple to array: <br>
[[8 4 6]<br>
[1 2 3]]<br>

In [9]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


#### 8. Write a NumPy program to find common values between two arrays.
Expected Output: <br>
Array1: [ 0 10 20 40 60] <br>
Array2: [10, 30, 40] <br>
Common values between two arrays:<br>
[10 40]<Br>

In [10]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


#### 9. Write a NumPy program to append values to the end of an array. Go to the editor
Expected Output: <br>
Original array: <br>
[10, 20, 30]<br>
After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]<br>

In [11]:
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


#### 10. Write a NumPy program to create a new shape to an array without changing its data. <br>
Original data : [1,2,3,4,5,6] <br>
Reshape 3x2: <br>
[[1 2] <br>
[3 4] <br>
[5 6]] <br>
Reshape 2x3:<br>
[[1 2 3]<br>
[4 5 6]]<br>

In [12]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]
